INSERT INTO client(ID, FIRSTNAME, LASTNAME, AGE, HEIGHT, WEIGHT, HEARTBEATS, SCORE) VALUES
  (1, 'Sara', 'Fernandes', 29, 166, 52, 120, 99),
  (2, 'Rodrigo', 'David', 29, 180, 88, 150, 120),
  (3, 'Rute', 'Amaro', 41, 160, 48, 200, 150);


INSERT INTO habit(ID, SMOKING, DRINKING, TAKEDRUGS, RISKYJOB, SPORTS, BOOTCAMPCODECADET, NUMBEROFMEALS, RELATIONSHIONSHIP, PARENT) VALUES
  (1, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, 3, FALSE, FALSE),
  (2, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, 4, TRUE, FALSE),
  (3, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, 6, TRUE, FALSE);